(** File generated by coq-of-ocaml *)
Require Import Coq.extraction.Extraction.
Extraction Language OCaml.
Require Import ExtrOcamlBasic.
Require Import ExtrOcamlString.
Require Import String.

Axiom string_of_char_list : string -> string.
Extract Constant string_of_char_list => "fun cl -> (String.of_seq (List.to_seq cl))".

Axiom print_endline : string -> unit.
Extract Inlined Constant print_endline => "print_endline".

(** Init function; without side-effects in Coq *)
Definition init_module : unit := print_endline (string_of_char_list "Hello World!").

Extraction "extract.ml" init_module.
